### ISSUE TITLE
Use toggles instead of checkboxes

### ISSUE THREAD

**Issue by LyubomirT** [LyubomirT/lookaround#4]
Currently, in the settings panel, checkboxes are used (because they're how the browsers render them by default). It could be better to use stylized toggles (gray->green) for those as that makes the overall design seem more consistent.

**Comment by yashwanth0010** [comment]
Can I work on that and do I have to only change the HTML code or should change the logic too?

**Comment by LyubomirT** [comment]
Sure, I'll assign the issue to you. I believe that you will need both HTML/CSS, with, optionally,  a little bit of JS. As far as I know, this can be done using an HTML container (`<span>` in a `<label>` along with an input (checkbox) element, with a couple CSS rulesets, but I'm open to your suggestions.
